Verify version before continuing

diff --git a/bin/docker-compose b/bin/docker-compose
--- a/bin/docker-compose
+++ b/bin/docker-compose
@@ -9,6 +9,12 @@ function __main__() {
   MONGO_IMAGE="mongo:3.6"
   REDIS_IMAGE="redis:5.0"
 
+  if [[ ! "$SHARELATEX_IMAGE_VERSION" \
+          =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+    echo "ERROR: invalid version '${SHARELATEX_IMAGE_VERSION}'"
+    exit 1
+  fi
+
   # Load vars from the rc file
   # shellcheck disable=SC1090
   source "$RC_FILE"
