Fix pathing in bin/logs and bin/error-logs

diff --git a/bin/error-logs b/bin/error-logs
--- a/bin/error-logs
+++ b/bin/error-logs
@@ -2,6 +2,15 @@
 
 set -euo pipefail
 
+#### Detect Toolkit Project Root ####
+SCRIPT_PATH="$(realpath "${BASH_SOURCE[0]}")"
+SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
+TOOLKIT_ROOT="$(realpath "$SCRIPT_DIR/..")"
+if [[ ! -d "$TOOLKIT_ROOT/bin" ]] || [[ ! -d "$TOOLKIT_ROOT/config" ]]; then
+  echo "ERROR: could not find root of overleaf-toolkit project (inferred project root as '$TOOLKIT_ROOT')"
+  exit 1
+fi
+
 function usage() {
     echo "Usage: bin/error-logs [OPTIONS] [SERVICES...]"
     echo ""
@@ -32,7 +41,7 @@ function __main__() {
         exit
     fi
     # preserve the '==>' labels from tail output
-    bin/logs "$@" | grep -E '(^==>.*$|^.*level":50.*$)' --color=never
+    "$TOOLKIT_ROOT/bin/logs" "$@" | grep -E '(^==>.*$|^.*level":50.*$)' --color=never
 }
 
 __main__ "$@"
diff --git a/bin/logs b/bin/logs
--- a/bin/logs
+++ b/bin/logs
@@ -2,6 +2,15 @@
 
 set -euo pipefail
 
+#### Detect Toolkit Project Root ####
+SCRIPT_PATH="$(realpath "${BASH_SOURCE[0]}")"
+SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
+TOOLKIT_ROOT="$(realpath "$SCRIPT_DIR/..")"
+if [[ ! -d "$TOOLKIT_ROOT/bin" ]] || [[ ! -d "$TOOLKIT_ROOT/config" ]]; then
+  echo "ERROR: could not find root of overleaf-toolkit project (inferred project root as '$TOOLKIT_ROOT')"
+  exit 1
+fi
+
 DEFAULT_LINES=20
 
 function usage() {
@@ -65,7 +74,7 @@ function __main__() {
 
     bash_exec_command_string="tail $FOLLOW_FLAG -n $LINES $path_spec"
 
-    exec ./bin/docker-compose exec sharelatex bash -c "$bash_exec_command_string"
+    exec "$TOOLKIT_ROOT/bin/docker-compose" exec sharelatex bash -c "$bash_exec_command_string"
 }
 
 __main__ "$@"
