Fix pathing in bin/images

diff --git a/bin/images b/bin/images
--- a/bin/images
+++ b/bin/images
@@ -2,6 +2,16 @@
 
 set -uo pipefail
 
+#### Detect Toolkit Project Root ####
+SCRIPT_PATH="$(realpath "${BASH_SOURCE[0]}")"
+SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
+TOOLKIT_ROOT="$(realpath "$SCRIPT_DIR/..")"
+if [[ ! -d "$TOOLKIT_ROOT/bin" ]] || [[ ! -d "$TOOLKIT_ROOT/config" ]]; then
+  echo "ERROR: could not find root of overleaf-toolkit project (inferred project root as '$TOOLKIT_ROOT')"
+  exit 1
+fi
+
+
 function usage() {
     echo "Usage: bin/images"
     echo ""
