Fix pathing in a bunch of bin scripts

diff --git a/bin/stop b/bin/stop
--- a/bin/stop
+++ b/bin/stop
@@ -1,9 +1,17 @@
 #! /usr/bin/env bash
 
 set -euo pipefail
+#### Detect Toolkit Project Root ####
+SCRIPT_PATH="$(realpath "${BASH_SOURCE[0]}")"
+SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
+TOOLKIT_ROOT="$(realpath "$SCRIPT_DIR/..")"
+if [[ ! -d "$TOOLKIT_ROOT/bin" ]] || [[ ! -d "$TOOLKIT_ROOT/config" ]]; then
+  echo "ERROR: could not find root of overleaf-toolkit project (inferred project root as '$TOOLKIT_ROOT')"
+  exit 1
+fi
 
 function __main__() {
-  exec ./bin/docker-compose stop "$@"
+  exec "$TOOLKIT_ROOT/bin/docker-compose" stop "$@"
 }
 
 __main__ "$@"
diff --git a/bin/up b/bin/up
--- a/bin/up
+++ b/bin/up
@@ -1,9 +1,18 @@
 #! /usr/bin/env bash
 
 set -euo pipefail
+#### Detect Toolkit Project Root ####
+SCRIPT_PATH="$(realpath "${BASH_SOURCE[0]}")"
+SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
+TOOLKIT_ROOT="$(realpath "$SCRIPT_DIR/..")"
+if [[ ! -d "$TOOLKIT_ROOT/bin" ]] || [[ ! -d "$TOOLKIT_ROOT/config" ]]; then
+  echo "ERROR: could not find root of overleaf-toolkit project (inferred project root as '$TOOLKIT_ROOT')"
+  exit 1
+fi
 
 function check_config() {
-  if [[ ! -f config/overleaf.rc ]] || [[ ! -f config/variables.env ]]; then
+  if [[ ! -f "$TOOLKIT_ROOT/config/overleaf.rc" ]] \
+      || [[ ! -f "$TOOLKIT_ROOT/config/variables.env" ]]; then
     echo "Config files not found! exiting"
     exit 1
   fi
@@ -11,7 +20,7 @@ function check_config() {
 
 function __main__() {
   check_config
-  exec ./bin/docker-compose up
+  exec "$TOOLKIT_ROOT/bin/docker-compose" up
 }
 
 __main__ "$@"
